import type { Metadata } from "next";
import ReactQueryProvider from "./providers";
import AuthSession from "./authSession";
import "@/styles/global.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AuthSession>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </AuthSession>
      </body>
    </html>
  );
}
